package com.talentbridge.enums;
public enum NotificationType {
    ACCOUNT_APPROVED, ACCOUNT_REJECTED, PARTY_JOINED, PARTY_LEFT,
    PROJECT_ASSIGNED, PROJECT_REJECTED, APPLICATION_SUBMITTED,
    SUBMISSION_RECEIVED, EVALUATION_COMPLETE, DEADLINE_REMINDER,
    NEW_PROJECT_POSTED, GENERAL
}
